# -*- coding: utf-8 -*-
"""
/***************************************************************************
 buffer_batch
                                 A QGIS plugin
 buffer_batch
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-20
        copyright            : (C) 2023 by mh
        email                : mh.cho058@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load buffer_batch class from file buffer_batch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .buffer_batch import buffer_batch
    return buffer_batch(iface)
