name: Create Release and Upload Asset

on:
  push:
    branches:
      - develop

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Create ZIP file
        run: |
          zip -r ${GITHUB_REPOSITORY}-.zip . -x "*.git*" -x "*.github*"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Increment tag version
        id: increment_tag
        run: |
          TAG=${{ env.TAG }}
          VERSION=${TAG#v}
          IFS='.' read -r -a version <<< "$VERSION"
          major=${version[0]}
          minor=${version[1]}
          patch=${version[2]}
          patch=$((patch + 1))
          NEW_TAG="v${major}.${minor}.${patch}"
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: buffer_batch develop-v${{ env.NEW_TAG }}
          body: |
            ### Release Notes for ${{ env.NEW_TAG }}

            - **Release Date**: ${{ github.event.head_commit.timestamp }}
            - **Changes**:
              - Added new features
              - Fixed bugs
              - Improved performance

            - **Installation**:
              - Download the ZIP file attached to this release.
              - Follow the installation instructions in the README file.

            - **Credits**:
              - Thanks to all contributors and testers!
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${GITHUB_REPOSITORY}-.zip
          asset_name: ${GITHUB_REPOSITORY}-.zip
          asset_content_type: application/zip

      - name: Upload to buffer_batch_plugin repository
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -X PUT \
               -T "${GITHUB_REPOSITORY}-.zip" \
               "https://api.github.com/repos/MHJO/qgis_plugin_repository/contents/buffer_batch_plugin/${{ env.NEW_TAG }}-${{ github.repository }}.zip" \
               -d '{"message":"Add release ZIP file","content":"$(base64 ${GITHUB_REPOSITORY}-.zip)"}'
